maintainer       "Dan Mallinger"
license          "Public"
description      "Installs/Configures Apache Hadoop"
version          "0.1.1"
recipe           "hadoop::default", "Installs Hadoop base libraries and conguration."
recipe           "hadoop::namenode", "Namenode specific config"
recipe           "hadoop::secondarynamenode", "Secondary namenode specific config"
recipe           "hadoop::jobtracker", "Jobtracker specific config"
recipe           "hadoop::slave", "Slave specific config"
depends          "java"
