maintainer       "Dan Mallinger"
license          "Public"
description      "Installs/Configures Apache Hive"
version          "0.1.1"
recipe           "hive::default", "Installs Hive"
depends          "hadoop"
